# ---------------------------------------------------------------------------------------------------------------------
# COMMON VARIABLES
# These variables are shared across all accounts and environments
# ---------------------------------------------------------------------------------------------------------------------

locals {
  # The external ID generated by Lucid that uniquely associates roles with the Lucid AWS proxy account
  # IMPORTANT: Replace this with your actual Lucid external ID
  external_id = "803889b5-9851-4a70-a0e0-8cfb9cac64b9"

  # Role naming conventions (keep consistent across all accounts)
  bastion_role_name        = "lucid-import-bastion-role"
  member_account_role_name = "lucid-import-account-role"
  bastion_policy_name      = "lucid-import-bastion-policy"
  member_policy_name       = "lucid-import-account-policy"

  # State backend configuration
  # IMPORTANT: Update these values for your organization
  state_bucket_name   = "torch-ai-lucid-import-tfstate"    # e.g., "torch-ai-lucid-import-tfstate"
  state_lock_table    = "lucid-import-tfstate-lock"      # e.g., "lucid-import-tfstate-lock"
  state_bucket_region = "us-east-1"                        # Region for the state bucket
}
